# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Release to GitHub

on:
  create:
    tags:
      - *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: github

      - name: Build with Maven
        run: mvn -B deploy -Dmaven.javadoc.skip=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}